version: "3.3"
services:
  database:
    build:
      context: .
      dockerfile: database.Dockerfile
    image: lordluch/gamix-database
    container_name: database
    restart: always
    volumes:
      - pg_data:/var/lib/postgres/data
    ports:
      - 5432:5432
    networks:
      - gamix_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: lordluch/gamix-back-end
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    networks:
      - gamix_network
    depends_on:
      - database
    links:
      - database

volumes:
  pg_data:

networks:
  gamix_network:
    driver: bridge