version: "3.1"
services:
  database:
    image: postgres:16-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    command: >
      -c config_file=/mnt/sda1/var/lib/postgresql/data/postgresql.conf
    volumes:
      - pg_data:/var/lib/postgres/data
      - ${PWD}/postgresql_conf/postgresql.conf:/mnt/sda1/var/lib/postgresql/data/postgresql.conf
    ports:
      - 5432:5432
    networks:
      - backend_network
  backend:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    container_name: backend
    restart: always
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SIGNING_KEY_SECRET=Graphql
      - FRONT_END_BASE_URL=http://localhost:3000
    volumes:
      - ./src:/app/src
      - ./graphql.config.yml:/app/graphql.config.yml
      - ./pom.xml:/app/pom.xml
      - ./target:/app/target
      - maven_cache:/root/.m2
    command: >
      /bin/sh -c './scripts/config_dev_env.sh && ./scripts/dev.sh'
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    networks:
      - backend_network
    depends_on:
      - database
    links:
      - database

volumes:
  pg_data:
  maven_cache:

networks:
  backend_network:
    driver: bridge