version: "3.1"
services:
  database:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    command: >
      -c config_file=/mnt/sda1/var/lib/postgresql/data/postgresql.conf
    volumes:
      - pg_data:/var/lib/postgres/data
      - ${PWD}/postgresql_conf/postgresql.conf:/mnt/sda1/var/lib/postgresql/data/postgresql.conf
    ports:
      - 5432:5432
    networks:
      - backend_network
  backend:
    build: .
    container_name: backend
    command: >
      /bin/sh -c "chmod +x wait-for-db.sh && ./wait-for-db.sh database 5432 && chmod +x run.sh && ./run.sh"
    volumes:
      - ./src:/app/src
      - ./run.sh:/app/run.sh
      - ./wait-for-db.sh:/app/wait-for-db.sh
    env_file:
      - .env
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - backend_network
    links:
      - database

volumes:
  pg_data:

networks:
  backend_network:
    driver: bridge