version: "3.3"
services:
  database:
    build:
      context: .
      dockerfile: database.Dockerfile
    container_name: database
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgres/data
    ports:
      - 5432:5432
    networks:
      - backend_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SIGNING_KEY_SECRET=${JWT_SIGNING_KEY_SECRET}
      - FRONT_END_BASE_URL=${FRONT_END_BASE_URL}
    ports:
      - 8080:8080
    networks:
      - backend_network
    depends_on:
      - database
    links:
      - database

volumes:
  pg_data:

networks:
  backend_network:
    driver: bridge