version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SIGNING_KEY_SECRET=${JWT_SIGNING_KEY_SECRET}
      - FRONT_END_BASE_URL=${FRONT_END_BASE_URL}
    ports:
      - 8080:8080