version: "3.3"
services:
  database:
    build:
      context: .
      dockerfile: database.Dockerfile
    container_name: database
    restart: always
    volumes:
      - pg_data:/var/lib/postgres/data
    ports:
      - 5432:5432
    networks:
      - backend_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend_network
    depends_on:
      - database
    links:
      - database

volumes:
  pg_data:

networks:
  backend_network:
    driver: bridge