version: "3.3"
services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SIGNING_KEY_SECRET=${JWT_SIGNING_KEY_SECRET}
      - FRONT_END_BASE_URL=${FRONT_END_BASE_URL}