version: "3.1"
services:
  database:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    command: >
      -c config_file=/mnt/sda1/var/lib/postgresql/data/postgresql.conf
    volumes:
      - pg_data:/var/lib/postgres/data
      - ${PWD}/postgresql_conf/postgresql.conf:/mnt/sda1/var/lib/postgresql/data/postgresql.conf
    ports:
      - 5432:5432
    networks:
      - backend_network
  backend:
    build: .
    container_name: backend
    restart: always
    environment:
      - "SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=root"
      - "JWT_SIGNING_KEY_SECRET=Graphql"
      - "FRONT_END_BASE_URL=http://localhost:3000"
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - backend_network

volumes:
  pg_data:

networks:
  backend_network: