@startuml Gamix-RefreshToken

actor User
participant Controller as "PasswordUserController"
participant PasswordService as "PasswordUserService"
participant JwtManager as "JwtManager"

User -> Controller: Faz uma requisição de refreshToken
Controller -> PasswordService: Chama o serviço de refreshToken
PasswordService --> JwtManager: Pede para gerar novos tokens JWT
JwtManager --> PasswordService: Retorna novos tokens JWT
PasswordService --> Controller: Retorna os novos tokens JWT
Controller --> User: Retorna os novos tokens JWT

@enduml
