@startuml Gamix-SignOut

actor User
participant Controller as "PasswordUserController"
participant PasswordService as "PasswordUserService"

User -> Controller: Faz uma requisição de SignOut
Controller -> PasswordService: Chama o serviço de SignOut
PasswordService --> Controller: Confirma a realização do SignOut
Controller --> User: Retorna confirmação de SignOut

@enduml
