@startuml Gamix-SignIn
actor User
participant Controller as "PasswordUserController"
participant PasswordService as "PasswordUserService"
participant Service as "UserService"
participant Repository as "UserRepository"
database Database as DB
participant JwtManager as "JwtManager"

User -> Controller: Faz uma requisição de signIn
Controller -> PasswordService: Chama o serviço de signIn
PasswordService -> Service: Pede para o Service o usuário
Service -> Repository: Busca o usuário no repositório
Repository -> DB: Consulta o banco de dados
DB --> Repository: Retorna os dados do usuário
Repository --> Service: Retorna o usuário
Service --> PasswordService: Retorna o usuário
PasswordService -> Service: Busca o PasswordUser
Service -> Repository: Busca o PasswordUser no repositório
Repository -> DB: Consulta o banco de dados
DB --> Repository: Retorna o PasswordUser
Repository --> Service: Retorna o PasswordUser
Service --> PasswordService: Retorna o PasswordUser
PasswordService --> JwtManager: Pede para gerar os tokens JWT
JwtManager --> PasswordService: Retorna os tokens JWT
PasswordService --> Controller: Retorna os tokens JWT
Controller --> User: Retorna os tokens JWT
@enduml
